### ISSUE TITLE
Tracking: v2.1

### ISSUE THREAD

**Issue by U-C-S** [The-UCS-Variable/the-ucs-variable.github.io#8]
- [x] Make Light theme UI more colorful
- [x] Add Status in About tab using gh-issues API
- [x] Footer Redesign (8c034e0fa1e0f9dbff2116e16e06ebc414fbc8b9)
  - Where Current Footer is converted to a Div and New Footer is added at the bottom of the Grid
  - Which contains other links and footer text

**Comment by U-C-S** [comment]
Another Redesign seems inevitable

**Comment by U-C-S** [comment]
Add a footer (This is a new addition i.e. A new rectangle at the Bottom) and Remove the body border. Let the Main Grid cover entire view and Footer is shown only when scrolled.

**Comment by U-C-S** [comment]
Use [Solid.js](https://www.solidjs.com/) for Web-Components and A Bundler like Parcel or Compiler like swc
